export const MODALS = {
  ADD_CITY: 'ADD_CITY',
  ADD_UNIT: 'ADD_UNIT',
  ADD_GROUP: 'ADD_GROUP',
  DELETE_CITY: 'DELETE_CITY',
  DELETE_UNIT: 'DELETE_UNIT',
  DELETE_GROUP: 'DELETE_GROUP',
  ADD_USER: 'ADD_USER'
};
